/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.ConexionBD;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Natalia
 */
public class Biblioteca extends javax.swing.JFrame {

    ConexionBD c = new ConexionBD();
    Connection con = c.getConexion();
    String attribute;
    
    /**
     * Creates new form insertBook
     */
    public Biblioteca() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBtnGroup = new javax.swing.ButtonGroup();
        AddNotaBtnGroup = new javax.swing.ButtonGroup();
        chooseTmaNotaBtnGroup = new javax.swing.ButtonGroup();
        PanelGeneral = new javax.swing.JTabbedPane();
        RegistroDeTodo = new javax.swing.JPanel();
        PanelRegistroArticulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ISSNArticuloRegistroTxtField = new javax.swing.JTextField();
        TituloArticuloRegistroTxtField = new javax.swing.JTextField();
        AutorArticuloRegistroTxtField = new javax.swing.JTextField();
        RevistaArticuloRegistroTxtField = new javax.swing.JTextField();
        PInicioArticuloRegistroTxtField = new javax.swing.JTextField();
        PFinArticuloRegistroTxtField = new javax.swing.JTextField();
        MesArticuloRegistroTxtField = new javax.swing.JTextField();
        YearArticuloRegistroTxtField = new javax.swing.JTextField();
        SaveArticuloRegistroBtn = new javax.swing.JButton();
        PanelRegistroLibro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ISBNLibroRegistroTxtField = new javax.swing.JTextField();
        TituloLibroRegistroTxtField = new javax.swing.JTextField();
        AutorLibroRegistroTxtField = new javax.swing.JTextField();
        EditorialLibroRegistroTxtField = new javax.swing.JTextField();
        PgNumLibroRegistroTxtField = new javax.swing.JTextField();
        YearLibroRegistroTxtField = new javax.swing.JTextField();
        SaveLibroRegistroBtn = new javax.swing.JButton();
        PanelBusqueda = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchBookComboBox = new javax.swing.JComboBox<>();
        libroSearchRadioBtn = new javax.swing.JRadioButton();
        ArticuloSearchRadioBtn = new javax.swing.JRadioButton();
        NotaSearchRadioBtn = new javax.swing.JRadioButton();
        searchComboTxtField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        exportarBtn = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        searchBookBtn = new javax.swing.JButton();
        searchArticleComboBox = new javax.swing.JComboBox<>();
        searchTmaComboBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        searchArticleBtn = new javax.swing.JButton();
        searchNotasBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        PanelNotas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        ApartadAniadirLibroEnNotasRadioBtn = new javax.swing.JRadioButton();
        ApartadoAniadirArticuloEnNotasRadioBtn = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        TemaTecnologiaDeNotaEnNotasRadioBtn = new javax.swing.JRadioButton();
        TemaHistoriaEnNotaRadioBtn = new javax.swing.JRadioButton();
        TemaOtroEnNotasRadioBtn = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        createNotaNotasTxtArea = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        valorEscritoAtributosSearchEnNotasTxtField = new javax.swing.JTextField();
        searchPorAtributoEnNotasComboBox = new javax.swing.JComboBox<>();
        createNotaNotasBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        showLibArtEnNotasTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        PanelModificar = new javax.swing.JPanel();
        PanelRegistroArticulo1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        PanelRegistroLibro2 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        RegistroDeTodo.setBackground(new java.awt.Color(204, 204, 255));

        PanelRegistroArticulo.setBackground(new java.awt.Color(153, 153, 255));
        PanelRegistroArticulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Registre su artículo");

        jLabel3.setText("ISSN");

        jLabel4.setText("Titulo");

        jLabel5.setText("Autor");

        jLabel6.setText("Revista");

        jLabel7.setText("Pagina de inicio");

        jLabel8.setText("Pagina de fin");

        jLabel9.setText("Mes");

        jLabel10.setText("Año");

        ISSNArticuloRegistroTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISSNArticuloRegistroTxtFieldActionPerformed(evt);
            }
        });

        TituloArticuloRegistroTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloArticuloRegistroTxtFieldActionPerformed(evt);
            }
        });

        AutorArticuloRegistroTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorArticuloRegistroTxtFieldActionPerformed(evt);
            }
        });

        PFinArticuloRegistroTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PFinArticuloRegistroTxtFieldActionPerformed(evt);
            }
        });

        SaveArticuloRegistroBtn.setText("Guardar");
        SaveArticuloRegistroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveArticuloRegistroBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistroArticuloLayout = new javax.swing.GroupLayout(PanelRegistroArticulo);
        PanelRegistroArticulo.setLayout(PanelRegistroArticuloLayout);
        PanelRegistroArticuloLayout.setHorizontalGroup(
            PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroArticuloLayout.createSequentialGroup()
                        .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRegistroArticuloLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelRegistroArticuloLayout.createSequentialGroup()
                                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelRegistroArticuloLayout.createSequentialGroup()
                                        .addComponent(ISSNArticuloRegistroTxtField)
                                        .addGap(79, 79, 79))
                                    .addGroup(PanelRegistroArticuloLayout.createSequentialGroup()
                                        .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(AutorArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TituloArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)))
                                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MesArticuloRegistroTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(YearArticuloRegistroTxtField))
                        .addGap(26, 26, 26))
                    .addGroup(PanelRegistroArticuloLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RevistaArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelRegistroArticuloLayout.createSequentialGroup()
                        .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PFinArticuloRegistroTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(PInicioArticuloRegistroTxtField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveArticuloRegistroBtn)
                        .addGap(18, 18, 18))))
        );
        PanelRegistroArticuloLayout.setVerticalGroup(
            PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ISSNArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(MesArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(TituloArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(YearArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AutorArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RevistaArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PInicioArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PFinArticuloRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(SaveArticuloRegistroBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelRegistroLibro.setBackground(new java.awt.Color(153, 153, 255));
        PanelRegistroLibro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Registre su libro");

        jLabel12.setText("ISBN");

        jLabel13.setText("Titulo");

        jLabel14.setText("Autor");

        jLabel15.setText("Editorial");

        jLabel16.setText("Numero de paginas");

        jLabel17.setText("Año");

        ISBNLibroRegistroTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNLibroRegistroTxtFieldActionPerformed(evt);
            }
        });

        TituloLibroRegistroTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloLibroRegistroTxtFieldActionPerformed(evt);
            }
        });

        AutorLibroRegistroTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorLibroRegistroTxtFieldActionPerformed(evt);
            }
        });

        YearLibroRegistroTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearLibroRegistroTxtFieldActionPerformed(evt);
            }
        });

        SaveLibroRegistroBtn.setText("Guardar");
        SaveLibroRegistroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveLibroRegistroBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistroLibroLayout = new javax.swing.GroupLayout(PanelRegistroLibro);
        PanelRegistroLibro.setLayout(PanelRegistroLibroLayout);
        PanelRegistroLibroLayout.setHorizontalGroup(
            PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLibroLayout.createSequentialGroup()
                        .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                                .addComponent(ISBNLibroRegistroTxtField)
                                .addGap(185, 185, 185))
                            .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AutorLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TituloLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(150, Short.MAX_VALUE))))
                    .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                        .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EditorialLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PgNumLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(148, Short.MAX_VALUE))
                    .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(YearLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveLibroRegistroBtn)
                        .addGap(18, 18, 18))))
        );
        PanelRegistroLibroLayout.setVerticalGroup(
            PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ISBNLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TituloLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AutorLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(EditorialLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PgNumLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearLibroRegistroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(SaveLibroRegistroBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegistroDeTodoLayout = new javax.swing.GroupLayout(RegistroDeTodo);
        RegistroDeTodo.setLayout(RegistroDeTodoLayout);
        RegistroDeTodoLayout.setHorizontalGroup(
            RegistroDeTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroDeTodoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(PanelRegistroArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(PanelRegistroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        RegistroDeTodoLayout.setVerticalGroup(
            RegistroDeTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroDeTodoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroDeTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRegistroArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelRegistroLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(325, 325, 325))
        );

        PanelGeneral.addTab("Registro", RegistroDeTodo);

        PanelBusqueda.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        searchBookComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchBookComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookComboBoxActionPerformed(evt);
            }
        });

        libroSearchRadioBtn.setText("Libros");

        ArticuloSearchRadioBtn.setText("Articulos");
        ArticuloSearchRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticuloSearchRadioBtnActionPerformed(evt);
            }
        });

        NotaSearchRadioBtn.setText("Notas");

        jLabel24.setText("Elija su criterio de búsqueda");

        exportarBtn.setText("Exportar");

        jLabel26.setText("¿Desea exportar los datos?");

        searchBookBtn.setText("Buscar");
        searchBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookBtnActionPerformed(evt);
            }
        });

        searchArticleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchTmaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setText("Si quiso notas, elija su tema");

        searchArticleBtn.setText("Buscar");

        searchNotasBtn.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(searchBookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchArticleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(39, 39, 39)
                                    .addComponent(searchComboTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(libroSearchRadioBtn)
                                    .addGap(27, 27, 27)
                                    .addComponent(ArticuloSearchRadioBtn)
                                    .addGap(28, 28, 28)
                                    .addComponent(NotaSearchRadioBtn)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchBookBtn)
                                    .addComponent(exportarBtn)
                                    .addComponent(searchArticleBtn)
                                    .addComponent(searchNotasBtn)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(searchTmaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libroSearchRadioBtn)
                    .addComponent(ArticuloSearchRadioBtn)
                    .addComponent(NotaSearchRadioBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTmaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(2, 2, 2)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchComboTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchArticleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(searchNotasBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchArticleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBookBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportarBtn)
                    .addComponent(jLabel26))
                .addGap(25, 25, 25))
        );

        searchTable.setBackground(new java.awt.Color(153, 255, 153));
        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(searchTable);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("¿Qué desea buscar?");

        javax.swing.GroupLayout PanelBusquedaLayout = new javax.swing.GroupLayout(PanelBusqueda);
        PanelBusqueda.setLayout(PanelBusquedaLayout);
        PanelBusquedaLayout.setHorizontalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBusquedaLayout.setVerticalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelGeneral.addTab("Búsqueda", PanelBusqueda);

        PanelNotas.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel18.setText("¿En qué apartado desea añadirla?");

        ApartadAniadirLibroEnNotasRadioBtn.setBackground(new java.awt.Color(255, 153, 153));
        ApartadAniadirLibroEnNotasRadioBtn.setText("Libro");
        ApartadAniadirLibroEnNotasRadioBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ApartadoAniadirArticuloEnNotasRadioBtn.setBackground(new java.awt.Color(255, 153, 153));
        ApartadoAniadirArticuloEnNotasRadioBtn.setText("Articulo");

        jLabel19.setText("Elija un tema para su nota");

        TemaTecnologiaDeNotaEnNotasRadioBtn.setText("Tecnologia");

        TemaHistoriaEnNotaRadioBtn.setText("Historia");

        TemaOtroEnNotasRadioBtn.setText("Otro");

        createNotaNotasTxtArea.setColumns(20);
        createNotaNotasTxtArea.setRows(5);
        jScrollPane2.setViewportView(createNotaNotasTxtArea);

        jLabel25.setText("Busque al que desee añadirla");

        searchPorAtributoEnNotasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createNotaNotasBtn.setText("Guardar");
        createNotaNotasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNotaNotasBtnActionPerformed(evt);
            }
        });

        showLibArtEnNotasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(showLibArtEnNotasTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(searchPorAtributoEnNotasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valorEscritoAtributosSearchEnNotasTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ApartadAniadirLibroEnNotasRadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(ApartadoAniadirArticuloEnNotasRadioBtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TemaTecnologiaDeNotaEnNotasRadioBtn)
                                    .addComponent(TemaOtroEnNotasRadioBtn)
                                    .addComponent(TemaHistoriaEnNotaRadioBtn)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(createNotaNotasBtn)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel25)
                    .addComponent(searchPorAtributoEnNotasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorEscritoAtributosSearchEnNotasTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApartadoAniadirArticuloEnNotasRadioBtn)
                    .addComponent(ApartadAniadirLibroEnNotasRadioBtn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(TemaTecnologiaDeNotaEnNotasRadioBtn))
                        .addGap(15, 15, 15)
                        .addComponent(TemaHistoriaEnNotaRadioBtn)
                        .addGap(16, 16, 16)
                        .addComponent(TemaOtroEnNotasRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createNotaNotasBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("¿Desea añadir una nota a algun libro o articulo?");

        javax.swing.GroupLayout PanelNotasLayout = new javax.swing.GroupLayout(PanelNotas);
        PanelNotas.setLayout(PanelNotasLayout);
        PanelNotasLayout.setHorizontalGroup(
            PanelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNotasLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelNotasLayout.setVerticalGroup(
            PanelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNotasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelGeneral.addTab("Notas", PanelNotas);

        PanelModificar.setBackground(new java.awt.Color(204, 153, 255));

        PanelRegistroArticulo1.setBackground(new java.awt.Color(204, 204, 255));
        PanelRegistroArticulo1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Articulo");

        jLabel29.setText("ISSN");

        jLabel30.setText("Titulo");

        jLabel31.setText("Autor");

        jLabel32.setText("Revista");

        jLabel33.setText("Pagina de inicio");

        jLabel34.setText("Pagina de fin");

        jLabel35.setText("Mes");

        jLabel36.setText("Año");

        jButton4.setText("Guardar");

        jButton8.setText("Modificar");

        javax.swing.GroupLayout PanelRegistroArticulo1Layout = new javax.swing.GroupLayout(PanelRegistroArticulo1);
        PanelRegistroArticulo1.setLayout(PanelRegistroArticulo1Layout);
        PanelRegistroArticulo1Layout.setHorizontalGroup(
            PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28)
                    .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField27))
                    .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField28))
                    .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                        .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField29, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jTextField30))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                        .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField38))
                            .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21))))
        );
        PanelRegistroArticulo1Layout.setVerticalGroup(
            PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addGap(14, 14, 14)
                .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroArticulo1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel35)
                            .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelRegistroArticulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel36)
                            .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroArticulo1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addContainerGap())))
        );

        PanelRegistroLibro2.setBackground(new java.awt.Color(153, 153, 255));
        PanelRegistroLibro2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel44.setText("Libro");

        jLabel45.setText("ISBN");

        jLabel46.setText("Titulo");

        jLabel47.setText("Autor");

        jLabel48.setText("Editorial");

        jLabel49.setText("Numero de paginas");

        jLabel50.setText("Año");

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });

        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });

        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });

        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });

        jButton7.setText("Guardar");

        jButton9.setText("Modificar");

        javax.swing.GroupLayout PanelRegistroLibro2Layout = new javax.swing.GroupLayout(PanelRegistroLibro2);
        PanelRegistroLibro2.setLayout(PanelRegistroLibro2Layout);
        PanelRegistroLibro2Layout.setHorizontalGroup(
            PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                        .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                                .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel46))
                                .addGap(18, 18, 18)
                                .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jTextField32, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel47)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                                .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel48)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel49)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(26, Short.MAX_VALUE))
                            .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLibro2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(54, 54, 54))
        );
        PanelRegistroLibro2Layout.setVerticalGroup(
            PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLibro2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(94, 94, 94))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout PanelModificarLayout = new javax.swing.GroupLayout(PanelModificar);
        PanelModificar.setLayout(PanelModificarLayout);
        PanelModificarLayout.setHorizontalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addComponent(PanelRegistroArticulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelRegistroLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelModificarLayout.setVerticalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRegistroArticulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelRegistroLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelGeneral.addTab("Modificar", PanelModificar);

        jLabel1.setText("BIBLIOTECA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ISSNArticuloRegistroTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISSNArticuloRegistroTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISSNArticuloRegistroTxtFieldActionPerformed

    private void TituloArticuloRegistroTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloArticuloRegistroTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloArticuloRegistroTxtFieldActionPerformed

    private void AutorArticuloRegistroTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorArticuloRegistroTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutorArticuloRegistroTxtFieldActionPerformed

    private void PFinArticuloRegistroTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PFinArticuloRegistroTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PFinArticuloRegistroTxtFieldActionPerformed

    private void ISBNLibroRegistroTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNLibroRegistroTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNLibroRegistroTxtFieldActionPerformed

    private void TituloLibroRegistroTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloLibroRegistroTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloLibroRegistroTxtFieldActionPerformed

    private void AutorLibroRegistroTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorLibroRegistroTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutorLibroRegistroTxtFieldActionPerformed

    private void YearLibroRegistroTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearLibroRegistroTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearLibroRegistroTxtFieldActionPerformed

    
    public int validaInt(String number){
    int result = 0; //Valor default.
    try{
        if((number != null)){
            result = Integer.parseInt(number);
        }
    }catch(NumberFormatException nfe){
        //*No es numerico!
    }
    return result;
}
    
    private void SaveArticuloRegistroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveArticuloRegistroBtnActionPerformed
         int PIni, PFin, Mes, Anio;
         PIni = validaInt(PInicioArticuloRegistroTxtField.getText());
         PFin = validaInt(PFinArticuloRegistroTxtField.getText());
         Mes = validaInt(MesArticuloRegistroTxtField.getText());
         Anio = validaInt(YearArticuloRegistroTxtField.getText());
         
         try {
            PreparedStatement pps = con.prepareStatement("INSERT INTO Articulo (ISSN, Titulo, Autor, Nom_revista, Pag_inicio, Pag_fin, Mes, Anio) VALUES (?,?,?,?,?,?,?,?)");
           
            if (TituloArticuloRegistroTxtField.getText().equals("") | AutorArticuloRegistroTxtField.getText().equals("") | RevistaArticuloRegistroTxtField.getText().equals("")){
                
                System.out.println("Error, ingrese titulo autor y revista");
            
            }else{
         
                pps.setString(1, ISSNArticuloRegistroTxtField.getText());
                pps.setString(2, TituloArticuloRegistroTxtField.getText());
                pps.setString(3, AutorArticuloRegistroTxtField.getText());
                pps.setString(4, RevistaArticuloRegistroTxtField.getText());
                pps.setInt(5, PIni);
                pps.setInt(6, PFin);
                pps.setInt(7, Mes);
                pps.setInt(8, Anio);

                pps.executeUpdate();        
                 
                JOptionPane.showMessageDialog(null, "Datos guardados");
            }   
        } catch (SQLException ex) {
            Logger.getLogger(Biblioteca.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SaveArticuloRegistroBtnActionPerformed

    private void searchBookComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBookComboBoxActionPerformed

    private void ArticuloSearchRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticuloSearchRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArticuloSearchRadioBtnActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void createNotaNotasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNotaNotasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNotaNotasBtnActionPerformed

    private void SaveLibroRegistroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveLibroRegistroBtnActionPerformed
        int nPag, Anio;
         nPag = validaInt(PgNumLibroRegistroTxtField.getText());
         Anio = validaInt(YearLibroRegistroTxtField.getText());
         
         try {
            PreparedStatement pps = con.prepareStatement("INSERT INTO Libro (ISBN, Titulo, Autor, Editorial, Numero_pags, Anio) VALUES (?,?,?,?,?,?)");
           
            if (TituloLibroRegistroTxtField.getText().equals("") | AutorLibroRegistroTxtField.getText().equals("")){
                
                System.out.println("Error, ingrese titulo y autor");
            
            }else{
         
                pps.setString(1, ISBNLibroRegistroTxtField.getText());
                pps.setString(2, TituloLibroRegistroTxtField.getText());
                pps.setString(3, AutorLibroRegistroTxtField.getText());
                pps.setString(4, EditorialLibroRegistroTxtField.getText());
                pps.setInt(5, nPag);
                pps.setInt(6, Anio);
  
                pps.executeUpdate();        
                 
                JOptionPane.showMessageDialog(null, "Datos guardados");
            }   
        } catch (SQLException ex) {
            Logger.getLogger(Biblioteca.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SaveLibroRegistroBtnActionPerformed

   public void showBookTableByAttribute (String value) {
        DefaultTableModel tablaLibro = new DefaultTableModel();
        tablaLibro.addColumn("Id");
        tablaLibro.addColumn("ISBN");
        tablaLibro.addColumn("Titulo");
        tablaLibro.addColumn("Nombre");
        tablaLibro.addColumn("Editorial");
        tablaLibro.addColumn("Numero de paginas");
        tablaLibro.addColumn("Año");

        searchTable.setModel(tablaLibro);
            
        String sql = "SELECT * FROM Libro WHERE " + attribute + "='" + value + "'";
            
        String columnasTabla [] = new String [7];
            
        try {   
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                columnasTabla [0] = rs.getString(1);
                columnasTabla [1] = rs.getString(2);
                columnasTabla [2] = rs.getString(3);
                columnasTabla [3] = rs.getString(4);
                columnasTabla [4] = rs.getString(5);
                columnasTabla [5] = rs.getString(6);
                columnasTabla [6] = rs.getString(7);

                                
                tablaLibro.addRow(columnasTabla);
            } 
            searchTable.setModel(tablaLibro);
        } catch (SQLException ex) {
            Logger.getLogger(Biblioteca.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    public void addItemsToBookComboBox() {
        searchBookComboBox.addItem("idLibro");
        searchBookComboBox.addItem("ISBN");
        searchBookComboBox.addItem("Titulo");
        searchBookComboBox.addItem("Autor");
        searchBookComboBox.addItem("Editorial");
        searchBookComboBox.addItem("Numero_pags");
        searchBookComboBox.addItem("Anio");
        
    }
    
     public void addItemsToArticleComboBox() {
         searchArticleComboBox.addItem("idArticulo");
        searchArticleComboBox.addItem("ISSN");
        searchArticleComboBox.addItem("Titulo");
        searchArticleComboBox.addItem("Autor");
        searchArticleComboBox.addItem("Nom_revista");
        searchArticleComboBox.addItem("Pag_inicio");
        searchArticleComboBox.addItem("Pag_fin");
        searchArticleComboBox.addItem("Mes");
        searchArticleComboBox.addItem("Anio");
    }
     
      public void addItemsToTemaComboBox() {
         searchTmaComboBox.addItem("idTema");
        searchTmaComboBox.addItem("Titulo");

    }
      
      
   

    private void searchBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookBtnActionPerformed
      
        attribute = searchBookComboBox.getSelectedItem().toString();
        showBookTableByAttribute(searchComboTxtField.getText());
        searchComboTxtField.setText("");
    }//GEN-LAST:event_searchBookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AddNotaBtnGroup;
    private javax.swing.JRadioButton ApartadAniadirLibroEnNotasRadioBtn;
    private javax.swing.JRadioButton ApartadoAniadirArticuloEnNotasRadioBtn;
    private javax.swing.JRadioButton ArticuloSearchRadioBtn;
    private javax.swing.JTextField AutorArticuloRegistroTxtField;
    private javax.swing.JTextField AutorLibroRegistroTxtField;
    private javax.swing.JTextField EditorialLibroRegistroTxtField;
    private javax.swing.JTextField ISBNLibroRegistroTxtField;
    private javax.swing.JTextField ISSNArticuloRegistroTxtField;
    private javax.swing.JTextField MesArticuloRegistroTxtField;
    private javax.swing.JRadioButton NotaSearchRadioBtn;
    private javax.swing.JTextField PFinArticuloRegistroTxtField;
    private javax.swing.JTextField PInicioArticuloRegistroTxtField;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JTabbedPane PanelGeneral;
    private javax.swing.JPanel PanelModificar;
    private javax.swing.JPanel PanelNotas;
    private javax.swing.JPanel PanelRegistroArticulo;
    private javax.swing.JPanel PanelRegistroArticulo1;
    private javax.swing.JPanel PanelRegistroLibro;
    private javax.swing.JPanel PanelRegistroLibro2;
    private javax.swing.JTextField PgNumLibroRegistroTxtField;
    private javax.swing.JPanel RegistroDeTodo;
    private javax.swing.JTextField RevistaArticuloRegistroTxtField;
    private javax.swing.JButton SaveArticuloRegistroBtn;
    private javax.swing.JButton SaveLibroRegistroBtn;
    private javax.swing.JRadioButton TemaHistoriaEnNotaRadioBtn;
    private javax.swing.JRadioButton TemaOtroEnNotasRadioBtn;
    private javax.swing.JRadioButton TemaTecnologiaDeNotaEnNotasRadioBtn;
    private javax.swing.JTextField TituloArticuloRegistroTxtField;
    private javax.swing.JTextField TituloLibroRegistroTxtField;
    private javax.swing.JTextField YearArticuloRegistroTxtField;
    private javax.swing.JTextField YearLibroRegistroTxtField;
    private javax.swing.ButtonGroup chooseTmaNotaBtnGroup;
    private javax.swing.JButton createNotaNotasBtn;
    private javax.swing.JTextArea createNotaNotasTxtArea;
    private javax.swing.JButton exportarBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JRadioButton libroSearchRadioBtn;
    private javax.swing.JButton searchArticleBtn;
    private javax.swing.JComboBox<String> searchArticleComboBox;
    private javax.swing.JButton searchBookBtn;
    private javax.swing.JComboBox<String> searchBookComboBox;
    private javax.swing.ButtonGroup searchBtnGroup;
    private javax.swing.JTextField searchComboTxtField;
    private javax.swing.JButton searchNotasBtn;
    private javax.swing.JComboBox<String> searchPorAtributoEnNotasComboBox;
    private javax.swing.JTable searchTable;
    private javax.swing.JComboBox<String> searchTmaComboBox;
    private javax.swing.JTable showLibArtEnNotasTable;
    private javax.swing.JTextField valorEscritoAtributosSearchEnNotasTxtField;
    // End of variables declaration//GEN-END:variables
}
